# Generated by Django 3.1 on 2020-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nm', models.CharField(max_length=264)),
                ('last_nm', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
